[server]
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[theme]
primaryColor = "#00B4D8"
backgroundColor = "#0A192F"
secondaryBackgroundColor = "#112240"
textColor = "#E6F1FF" 